### ISSUE TITLE
squash appveyor commits

### ISSUE THREAD

**Issue by patrickelectric** [progsource/maddy#20]
Is it possible to squash all appveyor commits ?
The commit history is a big dirty right now..

Such tests should be done in a different branch or in a fork

**Comment by progsource** [comment]
First of all - I developed that in a branch.

What I could have done would be to squash-merge it into the master in this particular case - but now it is already in the master, so I do not want to change the history anymore.

**Comment by patrickelectric** [comment]
I'm not saying that you have not done a branch for development. But before merging it to master branch, this commits could be squashed all in a single one, or at least in a minimum necessary to not pollute the master branch before the merge.

**Comment by patrickelectric** [comment]
And, since the repository does not have a huge commit activity, a squash in master in this moment does not hurts. But I respect your point of view.
