### ISSUE TITLE
Failing to build via cmake

### ISSUE THREAD

**Issue by patrickelectric** [progsource/maddy#23]
## Minimal Code Example

You can check the compilation here:
https://asciinema.org/a/Kb8RkuThHBgpkQs8ORkCltMmc

## Conditions

.                     | .
--------------------- | ------------------
**Operating System:** | Arch Linux
**Compiler:**         | gcc (GCC) 9.2.0
**Compiler flags:**   | Via CMake
**maddy version:**    | master branch

## Description

Tried to compile it via CMake

**Comment by progsource** [comment]
Can you please try it out with a newer version of gtest? (Go into the libs/gtest folder and checkout a newer version there)
