### ISSUE TITLE
Issue with parsing

### ISSUE THREAD

**Issue by sharadcodes** [progsource/maddy#26]
## Minimal Code Example

```
# Heading

<a href="abc.html">Link</a>
<a href="abc.html">Link</a>
<a href="abc.html">Link</a>
<a href="abc.html">Link</a>
```

I want to prevent those anchor tags from being surrounded with p tags

## Conditions

.                     | .
--------------------- | ------------------
**Operating System:** | Ubuntu 18.04
**Compiler:**         | g++
**Compiler flags:**   | none
**maddy version:**    | 1.1.0

## Description

How to prevent a specific portion of code from being rendered ?

**Comment by progsource** [comment]
With https://github.com/progsource/maddy/pull/27 this should be fixed.

**Comment by progsource** [comment]
Please try out version 1.1.1 with config like:
```cpp
auto config = std::make_shared<maddy::ParserConfig>();
config->isHTMLWrappedInParagraph = false;

auto parser = std::make_shared<maddy::Parser>(config);
const auto htmlOutput = parser->Parse(markdown);
```
and check if this solves your problem.

**Comment by sharadcodes** [comment]
@progsource  Thanks for the update will use it and see if it works.

**Comment by sharadcodes** [comment]
> Please try out version 1.1.1 with config like:
> 
> ```c++
> auto config = std::make_shared<maddy::ParserConfig>();
> config->isHTMLWrappedInParagraph = false;
> 
> auto parser = std::make_shared<maddy::Parser>(config);
> const auto htmlOutput = parser->Parse(markdown);
> ```
> 
> and check if this solves your problem.

Where to add it by the way ?

**Comment by sharadcodes** [comment]
It worked perfectly.
