### ISSUE TITLE
Add further configuration options to disable particular parsers

### ISSUE THREAD

**Issue by dspreadbury** [progsource/maddy#37]
I'm using Maddy to parse simple Markdown-like text and would find it useful to have more configuration options to disable particular parsers, in the same way that the `Config` object allows the emphasis parser to be disabled. I'd actually like to have only the parsers for bold/stong text and emphasis enabled, and disable everything else. It would be great to have some more members in the `Config` object to make this possible.

**Comment by progsource** [comment]
Sounds good to me. I'll put it on my todo list :)

**Comment by progsource** [comment]
This is now in master and will be in maddy with version 1.2.0.

```c++
config->enabledParsers = maddy::types::EMPHASIZED_PARSER | maddy::types::STRONG_PARSER;
```

**Comment by dspreadbury** [comment]
Thanks so much, Petra!
