### ISSUE TITLE
Vcpkg support

### ISSUE THREAD

**Issue by tsurumi-yizhou** [progsource/maddy#53]
### What are you missing in maddy?

When I seeking maddy on vcpkg, I found an "unofficial-maddy" repo and which contains the command of downloading file from this github repo. So I want to know whether you can add an official support on vcpkg, either the "unofficial" one is supported by official.

**Comment by progsource** [comment]
There is also an unofficial [conan](https://conan.io/center/recipes/maddy) and a [Fedora package](https://packages.fedoraproject.org/pkgs/maddy/maddy-devel/)
Because I personally don't use them currently in any project myself, I actually prefer the unofficial integrations for now.

**Comment by tsurumi-yizhou** [comment]
That's reasonable. Thx.
